site_name: My Docs
theme:
  name: material
extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: site/en/
      lang: en

    - name: 中文
      link: site/cn/
      lang: zh
