- file_path: cn/docs/cookies/amp.md
  run: 
    - [0, 1, 2]

- file_path: en/docs/cookies/amp.md
  run: 
    - [0, 1, 2]

# CODE BLOCK 3 REMOVED
# It's pseudo code

# grad_scaler = flow.amp.GradScaler(
#     init_scale=3000,
#     growth_factor=2.0,
#     backoff_factor=0.5,
#     growth_interval=1000,
# )
# self.set_grad_scaler(grad_scaler)
