- file_path: cn/docs/basics/05_autograd.md
  run:
    - [0, 1, 2, 4, 5, 6, 7, 9, 10]

- file_path: en/docs/basics/05_autograd.md
  run:
    - [0, 1, 2, 4, 5, 6, 7, 9, 10]

# REMOVE CODE BLOCK 3, 8. WRONG EXAMPLE:

# n1 = flow.tensor(10., requires_grad=True)
# n2 = flow.pow(n1, 2)
# n2.backward()
# n2.backward()

# x = flow.randn(1, 2, requires_grad=True)
# y = 3*x + 1
# y.backward()